import * as stylex from '@stylexjs/stylex'

export const styles = stylex.create({
  main: {
    minHeight: '100svh',
    color: 'var(--ink)',
    backgroundColor: 'var(--paper)',
  },
  hero: {
    minHeight: {
      default: '82svh',
      '@media (max-width: 1080px)': 'auto',
    },
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(0, 1.05fr) minmax(320px, 0.95fr)',
      '@media (max-width: 1080px)': '1fr',
    },
    alignItems: 'center',
    gap: {
      default: 48,
      '@media (max-width: 840px)': 28,
    },
    paddingTop: {
      default: 56,
      '@media (max-width: 840px)': 36,
    },
    paddingRight: {
      default: 40,
      '@media (max-width: 840px)': 20,
    },
    paddingBottom: 40,
    paddingLeft: {
      default: 40,
      '@media (max-width: 840px)': 20,
    },
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--line)',
    backgroundColor: 'var(--surface)',
  },
  heroCopy: {
    maxWidth: 780,
  },
  eyebrow: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 14,
    marginLeft: 0,
    color: 'var(--accent)',
    fontSize: 13,
    fontWeight: 800,
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  heroTitle: {
    maxWidth: 860,
    margin: 0,
    color: 'var(--ink)',
    fontSize: {
      default: 72,
      '@media (max-width: 840px)': 46,
    },
    lineHeight: 0.96,
    letterSpacing: 0,
  },
  lede: {
    maxWidth: 720,
    marginTop: 24,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: 'var(--muted)',
    fontSize: {
      default: 20,
      '@media (max-width: 840px)': 18,
    },
    lineHeight: 1.55,
  },
  heroActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 32,
  },
  linkButton: {
    minHeight: 40,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 0,
    paddingRight: 14,
    paddingBottom: 0,
    paddingLeft: 14,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: {
      default: 'var(--line-strong)',
      ':hover': 'var(--accent)',
    },
    borderRadius: 6,
    color: {
      default: 'var(--ink)',
      ':hover': 'var(--accent)',
    },
    backgroundColor: 'var(--surface)',
    fontWeight: 800,
    textDecoration: 'none',
  },
  pipeline: {
    width: {
      default: 'min(100%, 500px)',
      '@media (max-width: 1080px)': '100%',
    },
    margin: 0,
    padding: {
      default: 24,
      '@media (max-width: 840px)': 18,
    },
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--line)',
    borderRadius: 8,
    backgroundColor: 'var(--surface)',
    boxShadow: 'var(--shadow)',
  },
  pipelineNode: {
    minHeight: 92,
    display: 'grid',
    alignContent: 'center',
    gap: 8,
    padding: 18,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--line)',
    borderLeftWidth: 7,
    borderLeftStyle: 'solid',
    borderLeftColor: 'var(--teal)',
    borderRadius: 8,
    backgroundColor: 'var(--paper)',
  },
  pipelineNodeBuild: {
    borderLeftColor: 'var(--blue)',
  },
  pipelineNodeOutput: {
    borderLeftColor: 'var(--orange)',
  },
  pipelineNodeLabel: {
    color: 'var(--muted)',
    fontSize: 13,
    fontWeight: 800,
    textTransform: 'uppercase',
  },
  pipelineNodeStrong: {
    color: 'var(--ink)',
    fontSize: 22,
    lineHeight: 1.1,
  },
  pipelineRail: {
    width: 2,
    height: 32,
    marginRight: 'auto',
    marginLeft: 'auto',
    backgroundColor: 'var(--line-strong)',
  },
  section: {
    paddingTop: 56,
    paddingRight: {
      default: 40,
      '@media (max-width: 840px)': 20,
    },
    paddingBottom: 56,
    paddingLeft: {
      default: 40,
      '@media (max-width: 840px)': 20,
    },
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--line)',
    backgroundColor: 'var(--paper)',
  },
  sectionSurface: {
    backgroundColor: 'var(--surface)',
  },
  sectionHeading: {
    maxWidth: 880,
    marginBottom: 28,
  },
  sectionTitle: {
    margin: 0,
    color: 'var(--ink)',
    fontSize: {
      default: 40,
      '@media (max-width: 840px)': 32,
    },
    lineHeight: 1.08,
    letterSpacing: 0,
  },
  sectionDescription: {
    marginTop: 14,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    color: 'var(--muted)',
    fontSize: 18,
    lineHeight: 1.55,
  },
  summaryGrid: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(4, minmax(0, 1fr))',
      '@media (max-width: 1080px)': '1fr',
    },
    gap: 16,
    paddingTop: 24,
    paddingRight: {
      default: 40,
      '@media (max-width: 840px)': 20,
    },
    paddingBottom: 24,
    paddingLeft: {
      default: 40,
      '@media (max-width: 840px)': 20,
    },
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--line)',
    backgroundColor: 'var(--surface)',
  },
  card: {
    minWidth: 0,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--line)',
    borderRadius: 8,
    backgroundColor: 'var(--surface)',
  },
  summaryCard: {
    minHeight: 210,
    padding: 22,
  },
  metric: {
    width: 40,
    height: 40,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    color: 'var(--surface)',
    backgroundColor: 'var(--ink)',
    fontWeight: 900,
  },
  cardTitle: {
    marginTop: 18,
    marginRight: 0,
    marginBottom: 10,
    marginLeft: 0,
    color: 'var(--ink)',
    fontSize: 22,
    lineHeight: 1.18,
    letterSpacing: 0,
  },
  paragraph: {
    margin: 0,
    color: 'var(--muted)',
    lineHeight: 1.58,
  },
  grid2: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 1080px)': '1fr',
    },
    gap: 16,
  },
  grid3: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(3, minmax(0, 1fr))',
      '@media (max-width: 1080px)': '1fr',
    },
    gap: 16,
  },
  grid4: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(4, minmax(0, 1fr))',
      '@media (max-width: 1080px)': '1fr',
    },
    gap: 16,
  },
  autoGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: 16,
  },
  autoGridWide: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: 16,
  },
  simpleCard: {
    padding: 22,
  },
  simpleCardStrong: {
    display: 'block',
    marginTop: 16,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--line)',
    color: 'var(--ink)',
    fontWeight: 800,
    lineHeight: 1.55,
  },
  mechanicCard: {
    display: 'grid',
    alignContent: 'start',
    gap: 12,
    padding: 22,
  },
  mechanicStep: {
    width: 42,
    height: 42,
    display: 'inline-grid',
    placeItems: 'center',
    borderRadius: 999,
    color: 'var(--surface)',
    backgroundColor: 'var(--accent)',
    fontFamily: 'var(--mono)',
    fontWeight: 900,
  },
  mechanicOutput: {
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--line)',
    color: 'var(--ink)',
    fontWeight: 800,
    lineHeight: 1.55,
  },
  panel: {
    marginTop: 24,
    overflow: 'hidden',
  },
  panelHeading: {
    padding: 24,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--line)',
    backgroundColor: 'var(--surface)',
  },
  panelTitle: {
    margin: 0,
    color: 'var(--ink)',
    fontSize: 28,
    lineHeight: 1.18,
  },
  table: {
    backgroundColor: 'var(--surface)',
  },
  tableHead4: {
    display: {
      default: 'grid',
      '@media (max-width: 840px)': 'none',
    },
    gridTemplateColumns: '0.85fr repeat(3, minmax(0, 1fr))',
    color: 'var(--surface)',
    backgroundColor: 'var(--ink)',
    fontSize: 13,
    fontWeight: 900,
    textTransform: 'uppercase',
  },
  tableHead5: {
    display: {
      default: 'grid',
      '@media (max-width: 840px)': 'none',
    },
    gridTemplateColumns: '0.72fr repeat(3, minmax(0, 1.08fr)) 1.12fr',
    color: 'var(--surface)',
    backgroundColor: 'var(--ink)',
    fontSize: 13,
    fontWeight: 900,
    textTransform: 'uppercase',
  },
  tableRow4: {
    display: {
      default: 'grid',
      '@media (max-width: 840px)': 'block',
    },
    gridTemplateColumns: '0.85fr repeat(3, minmax(0, 1fr))',
    padding: {
      default: 0,
      '@media (max-width: 840px)': 18,
    },
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--line)',
  },
  tableRow5: {
    display: {
      default: 'grid',
      '@media (max-width: 840px)': 'block',
    },
    gridTemplateColumns: '0.72fr repeat(3, minmax(0, 1.08fr)) 1.12fr',
    padding: {
      default: 0,
      '@media (max-width: 840px)': 18,
    },
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--line)',
  },
  tableRow5First: {
    borderTopWidth: 0,
  },
  tableCell: {
    minWidth: 0,
    padding: {
      default: 18,
      '@media (max-width: 840px)': 0,
    },
    borderRightWidth: {
      default: 1,
      '@media (max-width: 840px)': 0,
    },
    borderRightStyle: 'solid',
    borderRightColor: 'var(--line)',
  },
  tableCellStacked: {
    marginTop: {
      default: 0,
      '@media (max-width: 840px)': 12,
    },
  },
  tableCellHighlight: {
    backgroundColor: 'var(--warm)',
    color: 'var(--ink)',
    padding: {
      default: 18,
      '@media (max-width: 840px)': 14,
    },
    borderRadius: {
      default: 0,
      '@media (max-width: 840px)': 6,
    },
  },
  tableCellLast: {
    borderRightWidth: 0,
  },
  tableHeading: {
    margin: 0,
    color: 'var(--ink)',
    fontSize: 17,
    lineHeight: 1.25,
  },
  liveDemoGrid: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(0, 1.12fr) minmax(360px, 0.88fr)',
      '@media (max-width: 1080px)': '1fr',
    },
    gap: 16,
  },
  playground: {
    display: 'grid',
    gap: 20,
    padding: {
      default: 24,
      '@media (max-width: 840px)': 18,
    },
  },
  playgroundHeading: {
    display: 'grid',
    gap: 8,
  },
  playgroundTitle: {
    margin: 0,
    color: 'var(--ink)',
    fontSize: 24,
    lineHeight: 1.15,
    letterSpacing: 0,
  },
  badge: {
    justifySelf: 'start',
    minHeight: 34,
    display: 'inline-flex',
    alignItems: 'center',
    paddingRight: 10,
    paddingLeft: 10,
    borderRadius: 6,
    color: 'var(--ink)',
    backgroundColor: 'var(--warm)',
    fontWeight: 900,
  },
  scenarioLabel: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 8,
    marginLeft: 0,
    color: 'var(--accent)',
    fontSize: 13,
    fontWeight: 900,
    textTransform: 'uppercase',
  },
  controlGrid: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(4, minmax(0, 1fr))',
      '@media (max-width: 1080px)': '1fr',
    },
    gap: 12,
  },
  fieldBox: {
    minWidth: 0,
    margin: 0,
    padding: 14,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--line)',
    borderRadius: 8,
    backgroundColor: 'var(--paper)',
  },
  legend: {
    marginBottom: 8,
    color: 'var(--ink)',
    fontSize: 13,
    fontWeight: 900,
    textTransform: 'uppercase',
  },
  optionLabel: {
    display: 'grid',
    gridTemplateColumns: 'auto minmax(0, 1fr)',
    alignItems: 'center',
    gap: 8,
  },
  optionLabelStacked: {
    marginTop: 8,
  },
  colorControl: {
    minWidth: 0,
    display: 'grid',
    gap: 8,
    padding: 14,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--line)',
    borderRadius: 8,
    backgroundColor: 'var(--paper)',
  },
  demoStage: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(0, 0.72fr) minmax(0, 1fr)',
      '@media (max-width: 1080px)': '1fr',
    },
    gap: 16,
    alignItems: 'stretch',
  },
  styleStack: {
    display: 'grid',
    alignContent: 'center',
    gap: 10,
    padding: 16,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--line)',
    borderRadius: 8,
    backgroundColor: 'var(--paper)',
  },
  stackItem: {
    minHeight: 38,
    display: 'flex',
    alignItems: 'center',
    paddingRight: 12,
    paddingLeft: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: 'var(--line-strong)',
    borderRadius: 6,
    color: 'var(--muted)',
    backgroundColor: 'rgba(255, 253, 248, 0.58)',
    fontWeight: 800,
  },
  stackItemActive: {
    borderStyle: 'solid',
    borderLeftWidth: 6,
    borderLeftStyle: 'solid',
    borderLeftColor: 'var(--accent)',
    color: 'var(--ink)',
    backgroundColor: 'var(--surface)',
  },
  demoCardPreview: {
    display: 'grid',
    alignContent: 'center',
    gap: 12,
    padding: 'var(--demo-padding)',
    borderWidth: 3,
    borderStyle: 'solid',
    borderColor: 'var(--demo-border)',
    borderRadius: 10,
    backgroundColor: 'var(--demo-bg)',
    color: 'var(--ink)',
    boxShadow: 'var(--shadow)',
    transitionProperty: 'border-color, padding, background-color',
    transitionDuration: '180ms',
    transitionTimingFunction: 'ease',
  },
  demoCardTitle: {
    color: 'var(--ink)',
    fontSize: 24,
    lineHeight: 1.1,
  },
  demoButton: {
    justifySelf: 'start',
    minHeight: 38,
    paddingRight: 12,
    paddingLeft: 12,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--ink)',
    borderRadius: 6,
    color: 'var(--surface)',
    backgroundColor: 'var(--ink)',
    fontWeight: 900,
  },
  callout: {
    margin: 0,
    padding: 14,
    borderLeftWidth: 6,
    borderLeftStyle: 'solid',
    borderLeftColor: 'var(--blue)',
    borderRadius: 6,
    color: 'var(--ink)',
    backgroundColor: 'var(--paper)',
    fontWeight: 800,
    lineHeight: 1.5,
  },
  dynamicControls: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 1080px)': '1fr',
    },
    gap: 12,
  },
  dynamicPreviewGrid: {
    display: 'grid',
    gap: 12,
  },
  dynamicPreview: {
    minWidth: 0,
    padding: 16,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--line)',
    borderLeftWidth: 8,
    borderLeftStyle: 'solid',
    borderLeftColor: 'var(--demo-border)',
    borderRadius: 8,
    backgroundColor: 'var(--paper)',
    transitionProperty: 'border-color',
    transitionDuration: '180ms',
    transitionTimingFunction: 'ease',
  },
  dynamicPreviewTitle: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 8,
    marginLeft: 0,
    color: 'var(--ink)',
    fontSize: 17,
  },
  dynamicPreviewBadge: {
    minHeight: 28,
    display: 'inline-flex',
    alignItems: 'center',
    marginBottom: 10,
    paddingRight: 9,
    paddingLeft: 9,
    borderRadius: 999,
    color: 'var(--surface)',
    backgroundColor: 'var(--demo-border)',
    fontSize: 13,
    fontWeight: 900,
  },
  timeline: {
    overflow: 'hidden',
  },
  timelineHead: {
    display: {
      default: 'grid',
      '@media (max-width: 840px)': 'none',
    },
    gridTemplateColumns: '0.8fr repeat(3, 1.25fr) 0.8fr',
    backgroundColor: 'var(--ink)',
    color: 'var(--surface)',
    fontSize: 13,
    fontWeight: 900,
    textTransform: 'uppercase',
  },
  timelineRow: {
    display: {
      default: 'grid',
      '@media (max-width: 840px)': 'block',
    },
    gridTemplateColumns: '0.8fr repeat(3, 1.25fr) 0.8fr',
    padding: {
      default: 0,
      '@media (max-width: 840px)': 18,
    },
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--line)',
  },
  timelineStrong: {
    display: 'flex',
    alignItems: 'center',
    color: 'var(--accent)',
    fontWeight: 800,
  },
  layerStack: {
    minHeight: 150,
    display: 'grid',
    alignContent: 'center',
    gap: 8,
    padding: 14,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--line)',
    borderRadius: 8,
    backgroundColor: 'var(--paper)',
  },
  layerItem: {
    display: 'block',
    width: 'calc(100% - var(--layer-index) * 18px)',
    minHeight: 38,
    alignContent: 'center',
    paddingRight: 12,
    paddingLeft: 12,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--line-strong)',
    borderLeftWidth: 6,
    borderLeftStyle: 'solid',
    borderLeftColor: 'var(--teal)',
    borderRadius: 6,
    backgroundColor: 'var(--surface)',
    color: 'var(--ink)',
    fontWeight: 800,
    transform: 'translateX(calc(var(--layer-index) * 18px))',
  },
  layerItemBlue: {
    borderLeftColor: 'var(--blue)',
  },
  layerItemOrange: {
    borderLeftColor: 'var(--orange)',
  },
  conflict: {
    padding: 14,
    borderLeftWidth: 6,
    borderLeftStyle: 'solid',
    borderLeftColor: 'var(--orange)',
    borderRadius: 6,
    backgroundColor: 'var(--warm)',
    color: 'var(--ink)',
    fontWeight: 800,
  },
  toolRead: {
    display: 'grid',
    gap: 12,
    margin: 0,
  },
  toolReadItem: {
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--line)',
  },
  term: {
    marginBottom: 4,
    color: 'var(--ink)',
    fontWeight: 900,
  },
  description: {
    margin: 0,
    color: 'var(--muted)',
    lineHeight: 1.55,
  },
  caseCard: {
    display: 'grid',
    gap: 20,
    padding: 24,
  },
  caseTop: {
    display: 'grid',
    gap: 10,
  },
  caseBody: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(3, minmax(0, 1fr))',
      '@media (max-width: 1080px)': '1fr',
    },
    gap: 12,
  },
  caseSignals: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 1080px)': '1fr',
    },
    gap: 12,
  },
  insetCard: {
    minWidth: 0,
    padding: 14,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--line)',
    borderRadius: 8,
    backgroundColor: 'var(--paper)',
  },
  insetWin: {
    borderLeftWidth: 6,
    borderLeftStyle: 'solid',
    borderLeftColor: 'var(--teal)',
  },
  insetRisk: {
    borderLeftWidth: 6,
    borderLeftStyle: 'solid',
    borderLeftColor: 'var(--orange)',
  },
  smallHeading: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 8,
    marginLeft: 0,
    color: 'var(--ink)',
    fontSize: 13,
    fontWeight: 900,
    textTransform: 'uppercase',
  },
  fitBars: {
    display: 'grid',
    gap: 14,
  },
  fitRow: {
    display: 'grid',
    gap: 7,
  },
  fitLabel: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    color: 'var(--ink)',
    fontSize: 14,
  },
  fitScore: {
    fontFamily: 'var(--mono)',
    fontWeight: 800,
  },
  fitTrack: {
    height: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--line)',
    borderRadius: 999,
    backgroundColor: 'var(--paper)',
  },
  fitFill: {
    display: 'block',
    width: 'var(--fit-score)',
    height: '100%',
    borderRadius: 'inherit',
    backgroundImage: 'linear-gradient(90deg, var(--teal), var(--blue))',
  },
  fitFillBlue: {
    backgroundImage: 'linear-gradient(90deg, var(--blue), var(--accent))',
  },
  fitFillOrange: {
    backgroundImage: 'linear-gradient(90deg, var(--orange), var(--focus))',
  },
  fitFillInk: {
    backgroundImage: 'linear-gradient(90deg, var(--accent), var(--ink))',
  },
  fitNote: {
    margin: 0,
    color: 'var(--muted)',
    fontSize: 14,
    lineHeight: 1.52,
  },
  cookbookList: {
    display: 'grid',
    gap: 20,
  },
  cookbookEntry: {
    padding: 22,
  },
  cookbookHeading: {
    maxWidth: 920,
    marginBottom: 18,
  },
  codeGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: 16,
  },
  codeCard: {
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    padding: 18,
  },
  codeCardTitle: {
    marginTop: 0,
    marginRight: 0,
    marginBottom: 10,
    marginLeft: 0,
    color: 'var(--ink)',
    fontSize: 16,
    lineHeight: 1.18,
  },
  codeTakeaway: {
    margin: 0,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--line)',
    color: 'var(--muted)',
    lineHeight: 1.55,
  },
  codeBlock: {
    width: '100%',
    minWidth: 0,
    maxWidth: '100%',
    marginTop: 'auto',
    marginRight: 0,
    marginBottom: 18,
    marginLeft: 0,
    overflowX: 'auto',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--line)',
    borderRadius: 8,
    backgroundColor: 'var(--code-bg)',
  },
  compositionCard: {
    display: 'flex',
    flexDirection: 'column',
    padding: 22,
    overflowWrap: 'anywhere',
  },
  splitList: {
    display: 'grid',
    gap: 16,
    marginTop: 22,
    marginRight: 0,
    marginBottom: 22,
    marginLeft: 0,
  },
  sourceLink: {
    alignSelf: 'flex-start',
    maxWidth: '100%',
    whiteSpace: 'normal',
  },
  decisionCard: {
    minHeight: 190,
    padding: 24,
    borderTopWidth: 6,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--teal)',
  },
  decisionCardBlue: {
    borderTopColor: 'var(--blue)',
  },
  decisionCardOrange: {
    borderTopColor: 'var(--orange)',
  },
  decisionCardFocus: {
    borderTopColor: 'var(--focus)',
  },
  evidenceGrid: {
    display: 'grid',
    gridTemplateColumns: {
      default: '0.9fr 1.1fr',
      '@media (max-width: 1080px)': '1fr',
    },
    gap: 16,
  },
  versions: {
    margin: 0,
  },
  versionRow: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    gap: 18,
    paddingTop: 11,
    paddingBottom: 11,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: 'var(--line)',
  },
  versionRowLast: {
    borderBottomWidth: 0,
  },
  versionName: {
    color: 'var(--muted)',
    fontFamily: 'var(--mono)',
    fontSize: 13,
  },
  versionValue: {
    margin: 0,
    color: 'var(--ink)',
    fontFamily: 'var(--mono)',
    fontWeight: 800,
  },
  sourceList: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 840px)': '1fr',
    },
    columnGap: 22,
    rowGap: 10,
    margin: 0,
    paddingLeft: 18,
  },
  sourceItem: {
    minWidth: 0,
    paddingLeft: 2,
    lineHeight: 1.35,
  },
  sourceItemLink: {
    overflowWrap: 'anywhere',
    lineHeight: 1.35,
  },
  footer: {
    display: 'flex',
    alignItems: {
      default: 'center',
      '@media (max-width: 840px)': 'flex-start',
    },
    justifyContent: 'space-between',
    flexDirection: {
      default: 'row',
      '@media (max-width: 840px)': 'column',
    },
    gap: 20,
    paddingTop: 24,
    paddingRight: {
      default: 40,
      '@media (max-width: 840px)': 20,
    },
    paddingBottom: 24,
    paddingLeft: {
      default: 40,
      '@media (max-width: 840px)': 20,
    },
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: 'var(--line)',
    backgroundColor: 'var(--ink)',
  },
  footerText: {
    margin: 0,
    color: 'rgba(255, 253, 248, 0.78)',
    fontSize: 14,
    lineHeight: 1.5,
  },
  footerNav: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: {
      default: 'flex-end',
      '@media (max-width: 840px)': 'flex-start',
    },
    gap: 10,
  },
  footerLink: {
    minHeight: 36,
    display: 'inline-flex',
    alignItems: 'center',
    paddingRight: 11,
    paddingLeft: 11,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: {
      default: 'rgba(255, 253, 248, 0.24)',
      ':hover': 'var(--focus)',
    },
    borderRadius: 6,
    color: {
      default: 'var(--surface)',
      ':hover': 'var(--focus)',
    },
    fontSize: 14,
    fontWeight: 800,
    textDecoration: 'none',
  },
})
